# Generated by Django 4.2.7 on 2025-11-19 10:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Judul Buku')),
                ('author', models.CharField(max_length=200, verbose_name='Penulis')),
                ('publisher', models.CharField(max_length=200, verbose_name='Penerbit')),
                ('year_published', models.IntegerField(verbose_name='Tahun Terbit')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('category', models.CharField(choices=[('fiksi', 'Fiksi'), ('non_fiksi', 'Non-Fiksi'), ('referensi', 'Referensi'), ('majalah', 'Majalah'), ('komik', 'Komik')], max_length=20, verbose_name='Kategori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/', verbose_name='Cover Buku')),
                ('total_copies', models.IntegerField(default=1, verbose_name='Jumlah Salinan')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buku',
                'verbose_name_plural': 'Buku',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.IntegerField(verbose_name='Nomor Salinan')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Barcode')),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='books/barcodes/')),
                ('condition', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat')], default='baik', max_length=20, verbose_name='Kondisi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Buku')),
            ],
            options={
                'verbose_name': 'Salinan Buku',
                'verbose_name_plural': 'Salinan Buku',
                'ordering': ['book', 'copy_number'],
                'unique_together': {('book', 'copy_number')},
            },
        ),
    ]
