# Generated by Django 4.2.7 on 2025-11-19 10:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Pinjam')),
                ('due_date', models.DateTimeField(verbose_name='Tanggal Jatuh Tempo')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Kembali')),
                ('status', models.CharField(choices=[('dipinjam', 'Dipinjam'), ('terlambat', 'Terlambat'), ('dikembalikan', 'Dikembalikan')], default='dipinjam', max_length=20, verbose_name='Status')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Jumlah Denda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcopy', verbose_name='Salinan Buku')),
            ],
            options={
                'verbose_name': 'Peminjaman',
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-borrowed_date'],
            },
        ),
    ]
